simulator_name: whacamole_constrained
project: unity

simulation:
  bm_model:
    cls: MoblArmsWrist
    kwargs:
      shoulder_variant: none
      skull_rotation: [0.9961947, 0, 0, -0.0871557]
      effort_model:
        cls: CumulativeFatigue3CCr
        kwargs:
          weight: 1e-1
  task:
    cls: UnityEnv
    kwargs:
      unity_executable: apps/whac-a-mole-linux/build.x86_64
      app_args: [-condition, random]
      standalone: true # set to False for debugging (open the app in Unity editor)
      #port: 5555 # uncomment for debugging (connects to this port instead of finding a random open one)
      time_scale: 5
      gear: oculus-quest-1
      left_controller_enabled: false
#      left_controller_body: "hand"
#      left_controller_relpose: [-0.06694103, -0.00423279, 0.00806701, 0.79349534, 0.49238653, -0.24941408,  0.256346]
      right_controller_body: hand
      right_controller_relpose: [-0.06694103, -0.00423279, 0.00806701, 0.79349534,
        0.49238653, -0.24941408, 0.256346]
      headset_body: skull
      headset_relpose: [-0.10703, 0.001594, -0.19141, 0.7071068, 0.7071068, 0, 0]
  perception_modules:
  - cls: vision.UnityHeadset
    kwargs:
      resolution: [120, 80]   # must match dimensions used in unity
      channels: [1, 3]
  - cls: proprioception.BasicWithEndEffectorPosition
    kwargs:
      end_effector: [geom, hand_2distph]
  run_parameters:
    action_sample_freq: 20
    info_keywords: [[Points, final], [RewardUnsuccessfulContact, sum], [DistanceReward,
        sum], [EffortCost, sum], [failrateTarget0, final], [failrateTarget1, final],
      [failrateTarget2, final], [failrateTarget3, final], [failrateTarget4, final],
      [failrateTarget5, final], [failrateTarget6, final], [failrateTarget7, final],
      [failrateTarget8, final]]

rl:
  algorithm: PPO
  policy_type: policies.MultiInputActorCriticPolicyTanhActions
  policy_kwargs:
    activation_fn: torch.nn.LeakyReLU
    net_arch: [256, 256]
    log_std_init: 0.0
    features_extractor_class: feature_extractor.FeatureExtractor
    normalize_images: false
  lr:
    function: schedule.linear_schedule
    kwargs:
      initial_value: 5e-5
      min_value: 1e-7
      threshold: 0.8
  total_timesteps: 100_000_000
  device: cuda
  num_workers: 10
  nsteps: 4000
  batch_size: 1000
  target_kl: 1.0
  save_freq: 5_000_000
version: 1.1.0
package_name: unity_random_3ccr_1e1_v115
gym_name: uitb:unity_random_3ccr_1e1_v115-v0
built: '2024-07-17 15:54:44'
